name: RPConfigGUI
version: 1.3.0
author: Puyodead1
main: io.github.puyodead1.RPConfigGUI.RPConfigGUI
depend: [RandomPackage]
api-version: 1.14
commands:
  rpconfig:
    description: open settings menu